### ISSUE TITLE
Certain textures and models are invisible when using this mod

### ISSUE THREAD

**Issue by Yoshistar95** [MoreMcmeta/emissive-plugin#1]
Certain items in the inventory (and models when in either hand) are completely invisible whenever this mod is active

I've done the steps to see what was causing it and concluded it was this specific mod causing it

I'm running on Minecraft 1.19.4 with the following mods: (normally more mods, but this is for testing purpose)

fabric-api-0.83.0+1.19.4
moremcmeta-1.19.4-4.0.0-fabric
emissive-plugin-1.19.4-1.0.0-fabric

I noticed the following affected items were: Shulker boxes, beds, banners, conduit, chests (except barrel), mob heads and shield
Everything else is fine, I included screenshots of the creative tab showing the affected items.

![textures 1](https://github.com/MoreMcmeta/emissive-plugin/assets/19244108/886f22b6-cd88-4aa1-8058-a1b019f094d1)
![textures 2](https://github.com/MoreMcmeta/emissive-plugin/assets/19244108/7969d642-7202-4b73-b392-9d8739ce4e69)
![textures 3](https://github.com/MoreMcmeta/emissive-plugin/assets/19244108/6b005b3c-3155-4fa8-a3ee-50df95fa6e31)
![textures 4](https://github.com/MoreMcmeta/emissive-plugin/assets/19244108/f3fc2df2-fc4e-4088-8063-315def6d7c0c)
![textures 5](https://github.com/MoreMcmeta/emissive-plugin/assets/19244108/1419ce61-2449-4c2b-84f3-c4d667843026)

**Comment by soir20** [comment]
Thanks for reporting this issue; I'm able to reproduce it on my end. I'll start working on a fix.

**Comment by soir20** [comment]
I have a working fix. I will be testing it more to ensure I haven't broken anything else before release, which will hopefully come today or tomorrow.

**Comment by soir20** [comment]
Version 1.0.1, which contains a fix for this issue, has been released.
