### ISSUE TITLE
Stuttering when loading chunks with liquids

### ISSUE THREAD

**Issue by soir20** [MoreMcmeta/emissive-plugin#12]
**Describe the bug**
Significant stuttering occurs when using Quark, even when no resource packs are being used.

**To reproduce**
1. Load a world with Quark and its dependency, AutoRegLib. No resource packs are needed.

**Expected behavior**
No stuttering.

**Screenshots or videos**
None currently.

**Which Minecraft versions does this bug affect?**
1.19.2

**Mod loader**
Which mod loaders does this bug affect?
- [x] Forge
- [ ] Fabric

**Mods list**
MoreMcmeta, emissive plugin, Quark, AutoRegLib

**Resource pack**
None.

**Additional context**
Reported by @zaeonNineZero in #8.

**Comment by soir20** [comment]
@zaeonNineZero I've narrowed this down to a potential issue with emissive liquid overlays. I've disabled liquid overlays in this dev build. Can you check whether the stuttering issue is gone with this build?

[emissive-plugin-1.19.2-dev-no-liquid-overlay-forge.zip](https://github.com/MoreMcmeta/emissive-plugin/files/13223861/emissive-plugin-1.19.2-dev-no-liquid-overlay-forge.zip)

**Comment by zaeonNineZero** [comment]
Tested it in the limited mod instance with Quark, Create, and Mekanism, and the stuttering is gone. I also tested it in my larger modded setup and found no stuttering. Thanks for the help!

**Comment by soir20** [comment]
Thanks for confirming; I'll work on a full fix to resolve this issue (since the build just disables a feature lol). Hopefully, there will be a  2.0.2 release by this weekend.

**Comment by soir20** [comment]
@zaeonNineZero This build has liquid overlays re-enabled with a fix for the issue. Can you check whether the stuttering is also fixed in this build?

[emissive-plugin-1.19.2-dev-cache-spritefinder-forge.zip](https://github.com/MoreMcmeta/emissive-plugin/files/13235152/emissive-plugin-1.19.2-dev-cache-spritefinder-forge.zip)

**Comment by zaeonNineZero** [comment]
I tested the new build and found no stuttering, so this issue should be solved.

**Comment by soir20** [comment]
MoreMcmeta 2.0.2, which contains a fix for this issue, has been released. It will take a few minutes for the files to be approved by CurseForge. Please report any issues you encounter in the new version.
