### ISSUE TITLE
Armor's emissive effect glows in the wrong place in first person

### ISSUE THREAD

**Issue by loboazul0103** [MoreMcmeta/emissive-plugin#13]
**Describe the bug**

The glowing part of the armor shows up in strange places on the first-person view.

**To reproduce**

1. Install a shader mode like Oculus, and install the MoreMcmeta - Emissive plugin. (In the process, I installed Embeddium instead of Rubidium.)
2. Install and load the resource pack with the armor emissive image.
3. Turn on the shader. (During this process, we found that only a few shaders were experiencing this behavior - Complementary shaders)

**Expected behavior**

There is a strange afterimage of the armor on the screen. It moves, mimicking my actions, but always stays in the same place. It is rendered as if it is quite a distance away.

**Screenshots or videos**

![2023-11-11_05 28 07](https://github.com/MoreMcmeta/emissive-plugin/assets/41937422/f38a5a58-8418-4665-b317-fbc727cd29d1)
![2023-11-11_05 28 09](https://github.com/MoreMcmeta/emissive-plugin/assets/41937422/2716e6ac-9575-40af-8a67-fd0aaae4359a)
How it looks weird on the screen.
When my character moves, it moves with them.

![2023-11-11_05 28 15](https://github.com/MoreMcmeta/emissive-plugin/assets/41937422/13a09fac-1482-40e0-bda8-37ba33c07718)
This is how the corresponding armor glows.

**Which Minecraft versions does this bug affect?**

1.19.2

**Mod loader**

- [ ● ] Forge
- [  ] Fabric

**Mods list**

AmbientSounds_FORGE_v5.2.13_mc1.19.2
architectury-6.5.85-forge
AutoRegLib-1.8.2-55
balm-forge-1.19.2-4.6.0
citadel-2.1.4-1.19
CreativeCore_FORGE_v2.9.4_mc1.19.2
cupboard-1.19.2-2.1
DragonSurvival-1.19.2-05.11.2023
Ding-1.19.2-Forge-1.4.1
embeddium-0.2.7+mc1.19.2
embeddiumplus-1.19.2-v1.0.0
emissive-plugin-1.19.2-2.0.2-forge
Ender_Dragon_Loot1.19.2-1.0.6
EuphoriaPatcher-0.1.1-forge
ferritecore-5.0.3-forge
geckolib-forge-1.19-3.1.40
Iceberg-1.19.2-forge-1.1.4
InsaneLib-1.7.5-mc1.19.2
libraryferret-forge-1.19.2-4.0.0
lightspeed-1.19.2-1.0.5
memoryleakfix-forge-1.17+-1.0.0
moonlight-1.19.2-2.3.5-forge
moremcmeta-1.19.2-4.3.0-forge
oculus-mc1.19.2-1.6.9
reforgium-1.0.12a
resourcefullib-forge-1.19.2-1.1.24
smoothboot(reloaded)-mc1.19.2-0.0.2
spyglass_improvements-1.4+mc1.19+forge
supermartijn642corelib-1.1.15-forge-mc1.19.2
textrues_embeddium_options-0.1.1+mc1.19.2
vanilla-refresh-1.4.16h

**Resource pack**

[EDL.zip](https://github.com/MoreMcmeta/emissive-plugin/files/13323314/EDL.zip)
Only the resource packs for the corresponding mod armor have been uploaded.

**Additional context**

I have found that the issue does not appear when using other shaders, but does appear when using Complementary shaders. I don't know of any other problematic shaders.
I was previously using a different emissive mode, but I didn't have that issue then (ETF). I used the same shaders in the same way. I've only experienced this when using that mode. I've tested with multiple modes, wondering if this is a conflict with other modes, but with no clear results. The results were different with and without this mode.
It would be nice to see the exact logs, but I couldn't get a crash report because it wasn't a crash issue. I don't know if this will help, but I'll try to upload the last log.

[latest.log](https://github.com/MoreMcmeta/emissive-plugin/files/13323343/latest.log)

**Comment by soir20** [comment]
Thanks for reporting this issue. I have a few questions so I can narrow down where this afterimage is coming from:
* What are the coordinates of the armor afterimage? Is it at x=0, z=0?
* Does the afterimage disappear when you change to 3rd person?
* Does the afterimage disappear when you take off the ender dragon armor?

**Comment by loboazul0103** [comment]
First of all, I'd like to apologize for the late reply.

1. my guess is that its position is probably x=0, z=0, because it's completely obscured by the third-person crosshair.
2. It seems to 'disappear' - it's very small, but it seems to remain, because it's an afterimage that follows my vision.
3. When you remove that armor, the afterimage disappears. I haven't checked the emissive textures of the other armor, so I don't know if this is a problem specific to that armor.

**Comment by loboazul0103** [comment]
I wasn't sure about this answer, so I did some more testing.

![2023-11-13_16 33 33](https://github.com/MoreMcmeta/emissive-plugin/assets/41937422/3bd37703-3452-4cbb-a94c-465a98c3cc52)
![2023-11-13_16 33 58](https://github.com/MoreMcmeta/emissive-plugin/assets/41937422/5275c176-2d70-4d5a-bc57-aaef7d88c8c0)
![2023-11-13_16 32 54](https://github.com/MoreMcmeta/emissive-plugin/assets/41937422/2f35758e-410f-4e72-9a62-cf2d4cd9fe8d)

1. the exact position of these afterimages is not x=0, z=0. They change position depending on the field of view I am looking at. What is the same is that they are all not far from the center of my field of view.
 One thing is for sure, it 'exists' within the rendering distance of my field of view. If I put my field of view in water, it will appear to be submerged.

2. confirmed that it does not disappear. I checked by shifting the third-person view via Shoulder Surfing mode.

3. I noticed that emissive textures on other armors, including the default vanilla armor, also leave an afterimage. 


++
In first person, i see that the afterimage doesn't deviate much from its position.
![2023-11-13_16 52 00](https://github.com/MoreMcmeta/emissive-plugin/assets/41937422/2dc0ff1f-3d74-4132-88fd-3e869cb416b5)

**Comment by soir20** [comment]
Thanks for confirming. I've installed your full mods list and can't reproduce the issue; I actually can't see the emissive overlay on the dragon armor at all. I see this entry in your logs:
> [1111¿ù2023 06:17:15.884] [Render thread/INFO] [net.minecraft.server.packs.resources.ReloadableResourceManager/]: Reloading ResourceManager: Default, Mod Resources, DSS All, DSS LangPack, McµÕ±Ù¸ð.zip, Better_Wolves_V2.2.zip, __MoreMcmeta Internal__

Can you upload the DSS All, DSS LangPack, McµÕ±Ù¸ð.zip, and Better_Wolves_V2.2.zip resource packs? Furthermore, I don't see EDL.zip on this list--are you sure this is the same resource pack you're using in-game?

**Comment by soir20** [comment]
I'm able to reproduce the issue now; I needed to add the `assets` directory and move the OptiFine `emissive.properties` file under the `minecraft` namespace.

**Comment by loboazul0103** [comment]
Oh, I'm glad to hear you were able to reproduce it. I apologize if my explanation was unclear. The resource pack I'm currently using is too big to upload, so I extracted and uploaded just the armor resources separately.
If I understand correctly, I should have moved the emissive.properties file to the asset - minecraft file location in my resource pack?

**Comment by soir20** [comment]
Here is the pack I am currently using to test. (I also changed one of the emissive layers to all white so it's easier to see in the distance.) I have a local build where the issue is fixed, but the fix causes issues for certain entity overlays, so I'm going to try a different approach.
[EDL-fixed.zip](https://github.com/MoreMcmeta/emissive-plugin/files/13372010/EDL-fixed.zip)

**Comment by soir20** [comment]
Emissive plugin version 2.0.3, which fixes this issue, has been released. It also fixes an issue where the emissive armor overlays would render under the base layer. It will take a few minutes for the files to be approved by CurseForge. Thanks for reporting!
