### ISSUE TITLE
End portal tiles render incorrectly when Iris shaders are enabled and MoreMcmeta's emissive plugin is loaded

### ISSUE THREAD

**Issue by BlueJayofEvil** [MoreMcmeta/emissive-plugin#14]
**Describe the bug**
End portal tiles render incorrectly when Iris shaders are enabled (Rethinking Voxels and BSL were both used for testing) and MoreMcmeta's emissive plugin is enabled in the mods list.
Each tile renders the current end portal texture individually per tile in a uniform direction on each one.

**To reproduce**
**1.** Install Iris (and any required mods), MoreMcmeta and emissive plugin
**2.** Install a resource pack that changes the end portal texture and a shader for Iris
**3.** Activate an end portal (create one in a creative world for easier testing) and look at the texture with shaders on.
**4.** Repeat the process with and without the emissive plugin enabled and see the difference.

**Expected behavior**
End portal textures rendering as they usually do with shaders.

**Screenshots or videos**
Shaders enabled with the emissive plugin disabled
![shaders with no emissive plugin](https://github.com/MoreMcmeta/emissive-plugin/assets/1016034/c459b5a0-447f-45f1-bde7-609fbcbe0207)

Shaders with emissive plugin enabled
![shaders with emissive plugin 1](https://github.com/MoreMcmeta/emissive-plugin/assets/1016034/0e806b7e-2ee9-4a0a-ba86-6d95bab31fad)
![shaders with emissive plugin 2](https://github.com/MoreMcmeta/emissive-plugin/assets/1016034/22943f52-aeed-423c-a7ff-bde5362b3ef3)

Emissive plugin enabled with shaders disabled
_(for reference to show it only happens when the shaders + emissive plugin enabled)_
![portal without shaders](https://github.com/MoreMcmeta/emissive-plugin/assets/1016034/a709748b-01b6-432f-bdd5-db4c3ca1959d)

**Which Minecraft versions does this bug affect?**
1.20.2

**Mod loader**
Which mod loaders does this bug affect?
- [ ] Forge
- [X] Fabric
Forge was not tested.

**Mods list**
cloth-config-12.0.111-fabric
emissive-plugin-1.20.2-2.0.3-fabric.jar
fabric-api-0.90.7+1.20.2
fabric-language-kotlin-1.10.14+kotlin.1.9.20
ferritecore-6.0.1-fabric
indium-1.0.27+mc1.20.1
iris-mc1.20.2-1.6.10
lithium-fabric-mc1.20.2-0.12.0
modmenu-8.0.0
moremcmeta-1.20.2-4.4.1-fabric
sodium-extra-0.5.3+mc1.20.2-build.114
sodium-fabric-mc1.20.2-0.5.3

**Resource pack**
Nyan Cat End Portal (Colored Version)
https://www.planetminecraft.com/texture-pack/nyan-cat-end-portal/

**Shader**
Rethinking Voxels: https://modrinth.com/shader/rethinking-voxels
BSL: https://modrinth.com/shader/bsl-shaders
(I tried more than one to make sure it wasn't RVX causing the issue specifically)

**Additional context**
I created a fresh instance with only those mods and just the Nyan Cat resource pack to make sure none of my normal mods and resource packs may have been interfering. I was able to reproduce this issue with the more minimal set up described above.

**Comment by soir20** [comment]
Thanks for reporting; I've identified the portion of the emissive plugin's code that causes the incompatibility. I have an idea to work around the issue. I'll do some testing to see if it works.

**Comment by soir20** [comment]
MoreMcmeta emissive plugin v2.0.4, which contains a fix for this issue, has been released. It will take a few minutes for CurseForge to approve the files. Please report any issues you encounter with the new version.

**Comment by BlueJayofEvil** [comment]
Seems to be working fine now. 👍 

![2023-11-25_00 26 58](https://github.com/MoreMcmeta/emissive-plugin/assets/1016034/e84cec13-9cf5-4802-8622-34f924a5a1f5)

![2023-11-25_00 26 47](https://github.com/MoreMcmeta/emissive-plugin/assets/1016034/c3f0c350-f0c8-43d6-82b8-d9daa9392b53)

Thank you!
