### ISSUE TITLE
Some emissive textures turn off when I get too close with physics mod

### ISSUE THREAD

**Issue by Sanriaa** [MoreMcmeta/emissive-plugin#17]
**Describe the bug**
I noticed that some emissive textures turn off when I walk too close to them. I noticed it on emissive kelp plants and twisting vines in the nether

**To reproduce**
1. Install an emissive texture resource pack and test if any turn off when you get too close

**Expected behavior**
The emissive textures should not turn off when you approach them

**Screenshots or videos**
https://imgur.com/byEhTmC EMISSIVE FAR AWAY, TURNS OFF UP CLOSE
https://imgur.com/uqTHvBg FAR AWAY
https://imgur.com/erYRevj CLOSER

**Which Minecraft versions does this bug affect?**
Forge 1.19.2, fabric 1.20.1. I have 2 different servers with each mod loader, and this bug effects both

**Mod loader**
Which mod loaders does this bug affect?
- [yes ] Forge
- [yes ] Fabric

**Mods list**
Many... but notably oculus + embeddium on forge, iris + sodium on fabric

**Resource pack**
I use many resource packs but this is the one that makes kelp flowers glow: https://www.planetminecraft.com/texture-pack/magical-biomes-ocean/

**Additional context**
I also tried disabling shaders but the problem persists
This only happens for a few emissive textures. Other emissive textures, like ores, behave normally

**Comment by soir20** [comment]
Thanks for reporting. FYI, I likely won't be able to look at this until the weekend.

**Comment by Sanriaa** [comment]
Hey! I found out that this issue seems to be caused by having the minecraft physics mod active (https://minecraftphysicsmod.com/). Not sure if there is a fix other than disabling those specific blocks

**Comment by soir20** [comment]
Thanks for narrowing this down! When you say disabling those specific blocks, do you mean disabling them in the physics mod or disabling the emissive textures?

I would need to look at how that mod changes rendering, but it may be difficult/impossible to fix on the emissive plugin side without breaking other things.

**Comment by Sanriaa** [comment]
I mean disabling them in the physics mod. There's in-game customization options for toggling off specific blocks:) yea I figured there isn't much chance of a fix on your side, but at least others who use these two mods can now be aware!

**Comment by soir20** [comment]
It looks like this physics mod is closed source, so toggling the physics mod off for those blocks is going to be the best solution. It's possible to decompile Java programs and get decent source code, but I would most likely have to violate their license to do so. (I can't even find a license to say whether I am allowed to do this.)

Thanks for reporting and figuring out that it was the physics mod!
