### ISSUE TITLE
1.21 Build

### ISSUE THREAD

**Issue by dylanparry** [MoreMcmeta/emissive-plugin#24]
I was wondering if there will be a 1.21 build for this mod?

**Comment by soir20** [comment]
Yes, there will be a 1.21 build for the emissive plugin. There were a lot of Minecraft rendering changes in the most recent update that significantly impact the emissive plugin. I've worked through some issues but am still rewriting one portion of the code to fix another. There's some discussion on the MoreMcmeta core thread here: MoreMcmeta/core#85

**Comment by soir20** [comment]
The emissive plugin has been released for 1.21. Please create a new issue for any problems you encounter in the new version.
