### ISSUE TITLE
CTD on 1.21 version

### ISSUE THREAD

**Issue by Angeleskk** [MoreMcmeta/emissive-plugin#25]
**Describe the bug**
When loading a world while shaders are active, crashes to desktop

**To reproduce**
1. Start Minecraft with Sodium and the required mods
2. Load into any Minecraft world
3. Enable any shader

**Screenshots or videos**
Crash report: https://pastebin.com/zVX3yv49

**Which Minecraft versions does this bug affect?**
Minecraft 1.21

**Mod loader**
Which mod loaders does this bug affect?
- [ ] Fabric

**Mods list**
-emissive-plugin-1.21-2.0.4-fabric
-indium-1.0.34+mc1.21
-iris-1.7.3+mc1.21
-modmenu-11.0.1
-moremcmeta-1.21-4.4.7-fabric
-sodium-fabric-0.5.11+mc1.21
-fabric-api-0.100.8+1.21

**Resource pack**
Tested with and without using resource packs with same results

**Additional context**
I've tested with a larger mod list and got rid of all but the basics but it still crashes in the same way. However, it does not crash if shaders are not enabled both when you load the world and were not enabled the last time the world was loaded (if I turned shaders from 'on' to 'off' in the main menu, it would still crash when loading in on that instance). Also, Minecraft does not crash when this mod is not added. Unless I'm dumb and missed something obvious, I can't get it to work on this version of Minecraft

**Comment by soir20** [comment]
This is a compatibility issue with Iris. I already have a fix locally and am planning a release later today.

**Comment by soir20** [comment]
MoreMcmeta emissive plugin version 2.0.5 has been released to fix this issue. This version also fixes an issue with block entity emissive overlays with Sodium. Thanks for reporting; please open a new issue for any other problems you encounter in the new version.
