### ISSUE TITLE
Sodium 0.6.0 support

### ISSUE THREAD

**Issue by sternschnaube** [MoreMcmeta/emissive-plugin#27]

**Comment by soir20** [comment]
Can you add more detail to this ticket please? What issue(s) are you encountering with Sodium? Does this only affect the emissive plugin?

**Comment by sternschnaube** [comment]
Seems to be an issue of the Emissive Plugin.

https://pastebin.com/raw/ucBNqaxV

**Comment by soir20** [comment]
Moving this to the emissive repo to avoid confusion/duplicates

**Comment by vinnyg0621** [comment]
i'm having the same issue!

**Comment by soir20** [comment]
MoreMcmeta emissive plugin 1.21-2.0.6 adds support for Sodium 0.6 versions. As Sodium 0.6 is still in beta, it is possible that there will be other changes that cause an incompatibility. Please open a new issue if that occurs.

Please note that this new version does not include support for 1.21.3, which is being worked on separately.
